lowercaseOutputName: true
rules:
  - pattern: 'kafka.cluster<type=Partition, name=InSyncReplicasCount, topic=(.+), partition=(.+)><>Value'
    name: kafka_cluster_partition_insyncreplicascount
    type: GAUGE
    labels:
      topic: "$1"
      partition: "$2"

  - pattern: 'kafka.cluster<type=Partition, name=ReplicasCount, topic=(.+), partition=(.+)><>Value'
    name: kafka_cluster_partition_replicascount
    type: GAUGE
    labels:
      topic: "$1"
      partition: "$2"

  - pattern: 'kafka.controller<type=KafkaController, name=ActiveControllerCount><>Value'
    name: kafka_controller_kafkacontroller_activecontrollercount
    type: GAUGE

  - pattern: 'kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(market-data-.+|arbitration-audit)><>Count'
    name: kafka_server_brokertopicmetrics_messagesin_total
    type: COUNTER
    labels:
      topic: "$1"